#ifndef CONST_H
#define CONST_H


const int  MINOPPLEGGDAGER = 1;
const int  MAXOPPLEGGDAGER = 31;
const int  MINTELEFONNUMMER = 10000;
const int  MAXTELEFONNUMMER = 99999999;
const int  MINKIRKEAAR = 500;
const int  MAXKIRKEAAR = 2023;
const int  MINKIRKEKAPASITET = 100;
const int  MAXKIRKEKAPASITET = 100000;

#endif
